
  Resources:

    EC2RunInstanceFunction:
      Type: AWS::Lambda::Function
      Properties:
        FunctionName: EC2ListFunction
        Handler: lambda_function.lambda_handler
        Role:
          Fn::GetAtt:
          - MyLambdaRole
          - Arn
        Runtime: Python3.8
         Code:
          S3Bucket: "S3Bucketname"
          S3Key:  "lambdafunction.zip"

    MyEventName:
      Type: AWS::Events::Rule
      Properties:
        Description: An awesome periodic event
        Name: MyEventName
        ScheduleExpression: "rate(12 hours)"
        State: ENABLED
        RoleArn:
          Fn::GetAtt:
            - "MyLambdaRole"
            - "Arn"
        Targets:
          -
            Arn:
              Fn::GetAtt:
                - "EC2RunInstanceFunction"
                - "Arn"
            Id: "EC2RunInstanceFunction"
            Input: '{"Test": "True"}'

    MyLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: "/"
        RoleName: MyLambdaRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
                  - events.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: MyLambdaPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: "arn:aws:logs:*:*:log-group:/aws/lambda/*:*:*"
                 - Effect: Allow
                   Action:
                    - ec2:DescribeInstances
                   Resource: "*"
                  -Effect: Allow
                   Action:
                    - s3:PutObject
                    - s3:GetObject
                    - sns:Publish
                    - logs:CreateLogGroup
                   Resource: 
                    - arn:aws:s3:::S3bucketec2llist/*
                    - arn:aws:sns:*:56565645:sns-topic
              
    InvokeLambdaPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Fn::GetAtt:
          - EC2RunInstanceFunction
          - Arn
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn:
          Fn::GetAtt:
          - LambdaFunctionSchedule
          - Arn